fill_rec: fill_rec.o case_generator.o
	g++ fill_rec.o case_generator.o -o fill_rec

fill_rec.o: fill_rec.cpp
	g++ -c fill_rec.cpp -o fill_rec.o

case_generator.o: case_generator.cpp
	g++ -c case_generator.cpp -o case_generator.o